### PR TITLE
Update aws-sdk 2 to aws-sdk 3

### PR DESCRIPTION
**Pull request by schanjr**
Tested and verified on jruby-9.2.9.0

image

### CODE REVIEW

**Comment by schanjr** [comment]
@thomas07vt

**Comment by thomas07vt** [comment]
Thanks Stanley!

**Comment by schanjr** [comment]
Thank you @thomas07vt  good to see you still active on Git! 

I have a bit of problem pushing this gem as I'm not the owner. Would you mind packaging it and pushing to rubygems.org? It also need to increment to version 0.3.7

image

**Comment by schanjr** [comment]
@thomas07vt  Need your help pls. 

Please push the gem into rubygems.org. Otherwise the team at Autodesk may need to internalize this gem. 

`bundle exec rake install`
`gem login`
`gem push`

**Comment by thomas07vt** [comment]
One second while i push...

**Comment by thomas07vt** [comment]
@schanjr https://rubygems.org/gems/sqs_buffer has 0.3.7

**Pull request merged**
